BaseConfig:
  db_path: vectorstores/pondlehocky
  OPENAI_API_TYPE: Azure
  OPENAI_API_KEY: 5f77f653b73e42948a920b9c2e6f76d8
  OPENAI_DEPLOYMENT_VERSION: 2024-02-15-preview
  OPENAI_DEPLOYMENT_ENDPOINT: https://pl-ver-openai.openai.azure.com/
  OPENAI_DEPLOYMENT_NAME: gpt-35
  OPENAI_MODEL_NAME: gpt-35-turbo
  OPENAI_ADA_EMBEDDING_DEPLOYMENT_NAME: embedding
  OPENAI_ADA_EMBEDDING_MODEL_NAME: text-embedding-ada-002

AuthConfig:
  SECRET_KEY: "83daa0256a2289b0fb23693bf1f6034d44396675749244721a2b20e896e11662"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: 100
